"""create members table

Revision ID: 016f551c16ac
Revises: 19078e1e11bb
Create Date: 2024-09-17 19:40:38.976491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016f551c16ac'
down_revision = '19078e1e11bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
